--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-2
  namespace: argocd
  finalizers: 
    - resources-finalizer.argocd.argoproj.io 
spec:
  project: default 

  source:
    repoURL: https://github.com/gowtham014/argocd-local.git
    targetRevision: HEAD 
    path: ./manifests/
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: test
  
  syncPolicy: 
    syncOptions:
      - CreateNamespace=true 
    automated:
      prune: true
      selfHeal: true